ktor:
  application:
    modules:
      - org.jetbrains.edu.junie2middie.ApplicationKt.module
  deployment:
    port: 8080
  database:
    jdbcUrl: "jdbc:sqlite:data.db"
    user: ""
    password: ""
    maxPoolSize: 5
